services:
  mojo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODULAR_AUTH_KEY=key_value
    tty: true
    stdin_open: true
    volumes:
      - ./mojo/:/root/mojo
    working_dir: "/root/mojo"
